project:
  type: website
  output-dir: docs
  resources:
    - CNAME
    - vsierra_cv10.23.pdf

website:
  title: "Valentín Quiroz de la Sierra"
  site-url: https://delasierra.io
  description: "Yo'eme Social Worker & Postdoc at Johns Hopkins Center for Indigenous Health"
  open-graph:
    locale: en_US
  comments:
    utterances:
      repo: vqsierra/vqsierra
  navbar:
    right:
      - text: "Home"
        href: index.html
      - text: "Writing"
        href: writing
      - text: "Teaching"
        href: teaching
      - text: "Action"
        href: action/index.qmd
  page-footer:
    center: "© Copyright 2026 Valentín Quiroz de la Sierra. Except where otherwise noted, all text and images licensed CC-BY-NC 4.0."
format:
  html:
    theme: sandstone
    css: styles.css
